---
version: '3.2'

services:
  build_deployment_package:
    build: .
    # This uses the value of the LAMBDA_TAG environment variable from
    # the invoking environment but falls back to a default value.
    image: cisagov/kevsync_lambda:${LAMBDA_TAG:-latest}
    entrypoint: /opt/build_artifact.sh
    environment:
      # This uses the value of the BUILD_FILE_NAME environment variable
      # from the invoking environment but falls back to a default value.
      - BUILD_FILE_NAME=${BUILD_FILE_NAME:-lambda_build.zip}
    volumes:
      - ./src/build_artifact.sh:/opt/build_artifact.sh
      - .:/var/task/output
  run_lambda_locally:
    build: .
    # This uses the value of the LAMBDA_TAG environment variable from
    # the invoking environment but falls back to a default value.
    image: cisagov/kevsync_lambda:${LAMBDA_TAG:-latest}
    ports:
      - "9000:8080"
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
